/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ASelect: typeof import('ant-design-vue/es')['Select']
    SearchPlace: typeof import('./src/components/SearchPlace/SearchPlace.vue')['default']
    WeatherCard: typeof import('./src/components/WeatherCard/WeatherCard.vue')['default']
    WeatherSettings: typeof import('./src/components/WeatherSettings/WeatherSettings.vue')['default']
    WeatherWidget: typeof import('./src/components/WeatherWidget/WeatherWidget.vue')['default']
  }
}
